development:
  sessions:
    default:
      database: app_arthur_dev
      hosts: 
        - localhost:27017

test:
  sessions:
    default:
      database: app_arthur_test
      hosts: 
        - localhost:27017

staging:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

production: 
  clients: 
    default: 
      uri: "mongodb://heroku_0hz479ds:1h42avgffts7n37tqh5scep6ol@ds061676.mlab.com:61676/heroku_0hz479ds"